const Map<String, String> genresName = {
  '28': 'Ação',
  '12': 'Aventura',
  '16': 'Animação',
  '35': 'Comédia',
  '80': 'Crime',
  '99': 'Documentário',
  '18': 'Drama',
  '10751': 'Família',
  '14': 'Fantasia',
  '36': 'História',
  '27': 'Terror',
  '10402': 'Musical',
  '9648': 'Mistério',
  '10749': 'Romance',
  '878': 'Ficção científica',
  '10770': 'Cinema TV',
  '53': 'Thriller',
  '10752': 'Guerra',
  '37': 'Faroeste',
};

const Map<String, String> genresId = {
  'Ação': '28',
  'Aventura': '12',
  'Animação': '16',
  'Comédia': '35',
  'Crime': '80',
  'Documentário': '99',
  'Drama': '18',
  'Família': '10751',
  'Fantasia': '14',
  'História': '36',
  'Terror': '27',
  'Musical': '10402',
  'Mistério': '9648',
  'Romance': '10749',
  'Ficção científica': '878',
  'Cinema TV': '10770',
  'Thriller': '53',
  'Guerra': '10752',
  'Faroeste': '37',
};

const List<String> genresList = [
  'Ação',
  'Aventura',
  'Animação',
  'Comédia',
  'Crime',
  'Documentário',
  'Drama',
  'Família',
  'Fantasia',
  'História',
  'Terror',
  'Musical',
  'Mistério',
  'Romance',
  'Ficção científica',
  'Cinema TV',
  'Thriller',
  'Guerra',
  'Faroeste',
];

//TODO: Pegar da API se der tempo
